### ISSUE TITLE
Firefox no candidates responded

### ISSUE THREAD

**Issue by lherman-cs** [mycrl/turn-rs#105] opened 2024-11-23 03:05 UTC
**Describe the bug**
Use https://webrtc.github.io/samples/src/content/peerconnection/trickle-ice/ or write your own WebRTC on Firefox. Firefox created binding requests and turn-rs responded. But, Firefox rejected these candidates, it doesn't show up as local candidates on `about:webrtc`.

Coturn is also having this issue, https://github.com/coturn/coturn/issues/1438. But, Cloudflare TURN works fine.

**Expected behavior**
Expect some reflexive and relay candidates to be responded. 

**Desktop (please complete the following information):**
 - OS: Mac
 - Browser: Firefox
 - Version: 134

**Additional context**

Firefox with Cloudflare TURN Wireshark: https://drive.google.com/file/d/1FKsY89dtW8s4tgM_myHaSBBouuG7jhNj/view?usp=drive_link

Firefox with turn-rs Wireshark: https://drive.google.com/file/d/18XsnF7oSwtk_xycCP6LCE7fx05kCpOyO/view?usp=sharing

I haven't taken a look deeply into these packets. I'll keep this issue updated as I investigate more.

**Comment by mycrl** [comment] 2024-11-23 04:53
This looks like a bug, but I'm not sure, I'll investigate why firefox can't assign it.
I've added this task to the next iteration and will address it in the next release if it's a bug.
If it's non-standard behavior, that is, firefox doing this is not explicitly defined behavior in rfc, I'll see what happens and decide if it's compatible or not. But if there's no clear reason why it can't be compatible, I won't refuse to make it compatible.

**Comment by mycrl** [comment] 2024-11-23 07:34
@lherman-cs Thanks for spotting this, we didn't notice this issue since our test and production environments have always been chrome or google native webrtc, the cause of this issue is the incorrect generation of the `CRC Fingerprint` attribute of the stun message.

This is a long-standing issue, and has not been found to exist before because other stun client implementations are more forgiving of message integrity checking (I guess), so they don't reject the response just because the crc result is incorrect.

I will fix this bug in v3.2.

**Comment by mycrl** [comment] 2024-11-24 22:09
done: https://github.com/mycrl/turn-rs/pull/106

**Closed by mycrl** 2024-11-24 22:09 UTC
Labels: bug
